sudo: required
services:
  - docker
before_install:
  - docker build -t federicoviscomineterea/docker-react -f Dockerfile.dev .
script:
  - docker run federicoviscomineterea/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-102235348925"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
