sudo: required
services:
  - docker
before_install:
  - docker build -t federicoviscomineterea/docker-react -f Dockerfile.dev .
script:
  - docker run federicoviscomineterea/docker-react npm run test -- --coverage
