version: '3'
services:
  web:
    build:
      context:  C:/Users/federicov/kappamindcore/frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - C:/Users/federicov/kappamindcore/frontend:/app
